name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Update the version based on your project needs

      - name: Install dependencies
        run: |
          npm ci  # Use npm ci instead of npm install to install dependencies cleanly

      - name: Run tests
        run: npm test  # Ensure this matches the script name for running tests

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Only runs if the build job succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
          echo "Deploying to production server..."  # Add actual deploy commands here
